### ISSUE TITLE
Kanban Capstone

### ISSUE THREAD

**Issue by fed1k** [fed1k/KanbanBoard#21]
https://github.com/fed1k/KanbanBoard/projects/1
Team memebers : There are 3 team members.

**Comment by omar-labana** [comment]
# **Approved ✔️**

Hi team

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
